[package]
name = "RUST-BrainFuckCompiler"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"

[profile.dev]
opt-level = 3               # Use slightly better optimizations.
overflow-checks = false     # Disable integer overflow checks.